// <auto-generated />
using System;
using EnvironmentRepository.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EnvironmentRepository.Migrations
{
    [DbContext(typeof(EnvironmentDbContext))]
    partial class EnvironmentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EnvironmentRepository.Models.Config.Sirket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sirket");
                });

            modelBuilder.Entity("EnvironmentRepository.Models.Dynamic.VeriListesi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SirketId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SirketId");

                    b.ToTable("VeriListesi");
                });

            modelBuilder.Entity("EnvironmentRepository.Models.Kullanici.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EnvironmentRepository.Models.Kullanici.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("EnvironmentRepository.Models.Kullanici.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("EnvironmentRepository.Models.Musteri.Adres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdresTipId")
                        .HasColumnType("integer");

                    b.Property<int>("BolgeKodu")
                        .HasColumnType("integer");

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PostaKodu")
                        .HasColumnType("integer");

                    b.Property<string>("Satir1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Satir2")
                        .HasColumnType("text");

                    b.Property<string>("Sehir")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SirketId")
                        .HasColumnType("integer");

                    b.Property<int?>("UlkeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdresTipId")
                        .IsUnique();

                    b.HasIndex("SirketId");

                    b.HasIndex("UlkeId")
                        .IsUnique();

                    b.ToTable("Adres");
                });

            modelBuilder.Entity("EnvironmentRepository.Models.Musteri.AdresTip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SirketId")
                        .HasColumnType("integer");

                    b.Property<bool>("Varsayilan")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("SirketId");

                    b.ToTable("AdresTip");
                });

            modelBuilder.Entity("EnvironmentRepository.Models.Musteri.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("AdresId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Bakiye")
                        .HasColumnType("numeric");

                    b.Property<string>("CepTelefonu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailString")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("text")
                        .HasColumnName("Detay");

                    b.Property<int?>("Dyn_1")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Dyn_10")
                        .HasColumnType("numeric");

                    b.Property<int?>("Dyn_2")
                        .HasColumnType("integer");

                    b.Property<int?>("Dyn_3")
                        .HasColumnType("integer");

                    b.Property<int?>("Dyn_4")
                        .HasColumnType("integer");

                    b.Property<string>("Dyn_5")
                        .HasColumnType("text");

                    b.Property<string>("Dyn_6")
                        .HasColumnType("text");

                    b.Property<string>("Dyn_7")
                        .HasColumnType("text");

                    b.Property<string>("Dyn_8")
                        .HasColumnType("text");

                    b.Property<decimal?>("Dyn_9")
                        .HasColumnType("numeric");

                    b.Property<string>("Ekip")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email2")
                        .HasColumnType("text");

                    b.Property<string>("Faks")
                        .HasColumnType("text");

                    b.Property<decimal?>("Iskonto")
                        .HasColumnType("numeric");

                    b.Property<int?>("KategoriId")
                        .HasColumnType("integer");

                    b.Property<int?>("KaynakId")
                        .HasColumnType("integer");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RiskDurumu")
                        .HasColumnType("integer");

                    b.Property<int?>("SektorId")
                        .HasColumnType("integer");

                    b.Property<int?>("SirketId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<bool>("TakipDurumu")
                        .HasColumnType("boolean");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefon2")
                        .HasColumnType("text");

                    b.Property<int?>("TipId")
                        .HasColumnType("integer");

                    b.Property<string>("Unvan")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VergiDairesi")
                        .HasColumnType("text");

                    b.Property<int?>("VergiNo")
                        .HasColumnType("integer");

                    b.Property<string>("WebAdres")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdresId")
                        .IsUnique();

                    b.HasIndex("KategoriId")
                        .IsUnique();

                    b.HasIndex("KaynakId")
                        .IsUnique();

                    b.HasIndex("SektorId")
                        .IsUnique();

                    b.HasIndex("SirketId")
                        .IsUnique();

                    b.HasIndex("TipId")
                        .IsUnique();

                    b.ToTable("Musteri");
                });

            modelBuilder.Entity("EnvironmentRepository.Models.Musteri.MusteriKategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SirketId")
                        .HasColumnType("integer");

                    b.Property<bool>("Varsayilan")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("SirketId");

                    b.ToTable("MusteriKategori");
                });

            modelBuilder.Entity("EnvironmentRepository.Models.Musteri.MusteriKaynak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SirketId")
                        .HasColumnType("integer");

                    b.Property<bool>("Varsayilan")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("SirketId");

                    b.ToTable("MusteriKaynak");
                });

            modelBuilder.Entity("EnvironmentRepository.Models.Musteri.MusteriSektor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SirketId")
                        .HasColumnType("integer");

                    b.Property<bool>("Varsayilan")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("SirketId");

                    b.ToTable("MusteriSektor");
                });

            modelBuilder.Entity("EnvironmentRepository.Models.Musteri.MusteriTip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SirketId")
                        .HasColumnType("integer");

                    b.Property<bool>("Varsayilan")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("SirketId");

                    b.ToTable("MusteriTip");
                });

            modelBuilder.Entity("EnvironmentRepository.Models.Musteri.Ulke", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Isim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Ulke");
                });

            modelBuilder.Entity("KullaniciSirket", b =>
                {
                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<int>("SirketlerId")
                        .HasColumnType("integer");

                    b.HasKey("KullaniciId", "SirketlerId");

                    b.HasIndex("SirketlerId");

                    b.ToTable("KullaniciSirket");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EnvironmentRepository.Models.Dynamic.VeriListesi", b =>
                {
                    b.HasOne("EnvironmentRepository.Models.Config.Sirket", "Sirket")
                        .WithMany()
                        .HasForeignKey("SirketId");

                    b.Navigation("Sirket");
                });

            modelBuilder.Entity("EnvironmentRepository.Models.Kullanici.RefreshToken", b =>
                {
                    b.HasOne("EnvironmentRepository.Models.Kullanici.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("EnvironmentRepository.Models.Musteri.Adres", b =>
                {
                    b.HasOne("EnvironmentRepository.Models.Musteri.AdresTip", "Tip")
                        .WithOne()
                        .HasForeignKey("EnvironmentRepository.Models.Musteri.Adres", "AdresTipId");

                    b.HasOne("EnvironmentRepository.Models.Config.Sirket", "Sirket")
                        .WithMany()
                        .HasForeignKey("SirketId");

                    b.HasOne("EnvironmentRepository.Models.Musteri.Ulke", "Ulke")
                        .WithOne()
                        .HasForeignKey("EnvironmentRepository.Models.Musteri.Adres", "UlkeId");

                    b.Navigation("Sirket");

                    b.Navigation("Tip");

                    b.Navigation("Ulke");
                });

            modelBuilder.Entity("EnvironmentRepository.Models.Musteri.AdresTip", b =>
                {
                    b.HasOne("EnvironmentRepository.Models.Config.Sirket", "Sirket")
                        .WithMany()
                        .HasForeignKey("SirketId");

                    b.Navigation("Sirket");
                });

            modelBuilder.Entity("EnvironmentRepository.Models.Musteri.Musteri", b =>
                {
                    b.HasOne("EnvironmentRepository.Models.Musteri.Adres", "Adres")
                        .WithOne()
                        .HasForeignKey("EnvironmentRepository.Models.Musteri.Musteri", "AdresId");

                    b.HasOne("EnvironmentRepository.Models.Musteri.MusteriKategori", "Kategori")
                        .WithOne()
                        .HasForeignKey("EnvironmentRepository.Models.Musteri.Musteri", "KategoriId");

                    b.HasOne("EnvironmentRepository.Models.Musteri.MusteriKaynak", "Kaynak")
                        .WithOne()
                        .HasForeignKey("EnvironmentRepository.Models.Musteri.Musteri", "KaynakId");

                    b.HasOne("EnvironmentRepository.Models.Musteri.MusteriSektor", "Sektor")
                        .WithOne()
                        .HasForeignKey("EnvironmentRepository.Models.Musteri.Musteri", "SektorId");

                    b.HasOne("EnvironmentRepository.Models.Config.Sirket", "Sirket")
                        .WithOne()
                        .HasForeignKey("EnvironmentRepository.Models.Musteri.Musteri", "SirketId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("EnvironmentRepository.Models.Musteri.MusteriTip", "Tip")
                        .WithOne()
                        .HasForeignKey("EnvironmentRepository.Models.Musteri.Musteri", "TipId");

                    b.Navigation("Adres");

                    b.Navigation("Kategori");

                    b.Navigation("Kaynak");

                    b.Navigation("Sektor");

                    b.Navigation("Sirket");

                    b.Navigation("Tip");
                });

            modelBuilder.Entity("EnvironmentRepository.Models.Musteri.MusteriKategori", b =>
                {
                    b.HasOne("EnvironmentRepository.Models.Config.Sirket", "Sirket")
                        .WithMany()
                        .HasForeignKey("SirketId");

                    b.Navigation("Sirket");
                });

            modelBuilder.Entity("EnvironmentRepository.Models.Musteri.MusteriKaynak", b =>
                {
                    b.HasOne("EnvironmentRepository.Models.Config.Sirket", "Sirket")
                        .WithMany()
                        .HasForeignKey("SirketId");

                    b.Navigation("Sirket");
                });

            modelBuilder.Entity("EnvironmentRepository.Models.Musteri.MusteriSektor", b =>
                {
                    b.HasOne("EnvironmentRepository.Models.Config.Sirket", "Sirket")
                        .WithMany()
                        .HasForeignKey("SirketId");

                    b.Navigation("Sirket");
                });

            modelBuilder.Entity("EnvironmentRepository.Models.Musteri.MusteriTip", b =>
                {
                    b.HasOne("EnvironmentRepository.Models.Config.Sirket", "Sirket")
                        .WithMany()
                        .HasForeignKey("SirketId");

                    b.Navigation("Sirket");
                });

            modelBuilder.Entity("KullaniciSirket", b =>
                {
                    b.HasOne("EnvironmentRepository.Models.Kullanici.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnvironmentRepository.Models.Config.Sirket", null)
                        .WithMany()
                        .HasForeignKey("SirketlerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("EnvironmentRepository.Models.Kullanici.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("EnvironmentRepository.Models.Kullanici.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("EnvironmentRepository.Models.Kullanici.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("EnvironmentRepository.Models.Kullanici.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnvironmentRepository.Models.Kullanici.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("EnvironmentRepository.Models.Kullanici.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
